# Generated by Django 5.1.4 on 2025-01-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_county_latitude_alter_county_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='latitude',
            field=models.CharField(default='0.0', max_length=8),
        ),
        migrations.AlterField(
            model_name='county',
            name='longitude',
            field=models.CharField(default='0.0', max_length=8),
        ),
        migrations.AlterField(
            model_name='weather',
            name='latitude',
            field=models.CharField(default='0.0', max_length=8),
        ),
        migrations.AlterField(
            model_name='weather',
            name='longitude',
            field=models.CharField(default='0.0', max_length=8),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.CharField(default='0.0', max_length=8),
        ),
    ]
